version: '3.8'

services:
  db:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
"""
서버 도커 구축하면 사용
  backend:
    build: ./backend
		container_name: backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - C:\24-1CapStone-main\api
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    networks:
      - backend
    depends_on:
      - db
networks:
  backend:
  """